apimServiceName: AHCSA-APIMDemo-Prod
namedValues:
  - name: Environment
    displayName: Environment
    value: Prod
  
apis:
  - name: echo-api
    displayName: "Echo API"
    serviceUrl: "http://echoapi-prod.cloudapp.net/api"
