openapi: 3.0.1
info:
  title: wth31
  description: ''
  version: '1.0'
servers:
  - url: https://ahcsa-apimdemo-dev.azure-api.net
paths:
  /api:
    get:
      summary: Get Message
      operationId: get
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]